### ISSUE TITLE
Add Necessary Files for Packaging

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/packaging#1]
We need to upload all the necessary files to this repo that can be fetched by our script in our Jenkins job. This includes BUILD files as well as init scripts and anything else necessary to package the product.

The layout and versioning needs to be handled as well:

```
Version: $ce_version
    deb/
        $build_files
    rpm/
        $build_files
```

**Comment by nikdavnik** [comment]
All build files pushed to github
